- name: Install kubectl
  apt:
    deb: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubectl repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install kubectl
  apt:
    name: kubectl
    state: present
